---
- hosts: 172.31.31.52
  become: yes
  tasks:
  - include_tasks: myfile.yml

  - name: i want to install webserver
    apt:
     name: apache2
     state: present
  
  - name: I want to install restart the webserver
    apt:
     name: apache2
     state: restart