---
- hosts: 172.31.31.52
  become: yes
  tasks:
  - include_tasks: myfile.yml

- name: i want to install webserver
  apt:
   name: apache2
   state: present
   
- name: i want to restart the service
  service:
   name: apache2
   state: restart