---
- hosts: all
  become: yes
  tasks:
  - name: i want to install webserver on Ubuntu
    apt:
     name: apache2
     state: present
    when: ansible_os_family== "Debian"
  - name: i want to start webserver service on Ubuntu
    service:
     name: apache2
     state: started
    when: ansible_os_family== "Debian"


  - name: i want to install webserver on RedhatM
    yum:
     name: httpd
     state: present
    when: ansible_os_family== "RedHat"
  - name: I want to start webserver service on RedhatM
    service:
     name: apache2
     state: started
     when: ansible_os_family== "RedHat"