---
- hosts: all
  become: yes
  tasks:
  - name: i want to install webserver on Ubuntu
    apt:
     name: apache2
     state: present
    when: ansible_os_family== "Debian"
  - name: I want to install Webserver on Redhat mechine.
    yum:
     name: httpd
     state: present
     when: ansible_os_family== "RedHat"