---
- hosts: Webserver
  become: yes
  tasks:
  - name: i want to install webserver on Ubuntu
    apt:
     name: "{{myubuntuwebpackage}}"
     state: present
    when: ansible_os_family== "Debian"
  - name: i want to start webserver service on Ubuntu
    service:
     name: "{{myubuntuwebpackage}}"
     state: started
    when: ansible_os_family== "Debian"


  - name: i want to install webserver on Redhat
    yum:
     name: {{"myredhatwebpackage"}}
     state: present
    when: ansible_os_family== "RedHat"
  - name: i want to run webservice on Redhat
    service:
     name: {{"myredhatwebpackage"}}
     state: started
    when: ansible_os_family== "RedHat"